# This file was generated by GoReleaser. DO NOT EDIT.
class Bigfile < Formula
  desc "A file transfer system that supports http, rpc and ftp protocols"
  homepage "https://bigfile.site"
  version "1.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bigfile/bigfile/releases/download/v1.0.6/bigfile_1.0.6_darwin_amd64.tar.gz"
    sha256 "0e59780311680919ebd81b8fee95ffa64aa3c850113dfdc89e6f6ed5a405d3d5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bigfile/bigfile/releases/download/v1.0.6/bigfile_1.0.6_linux_amd64.tar.gz"
      sha256 "d1917a566bf6fba655670bc3f9ddef66d53885a5286a0060a60798464cbf813d"
    end
  end

  def install
    bin.install "bigfile"
  end

  def caveats; <<~EOS
    start mysql before starting bigfile
  EOS
  end

  test do
    system "#{bin}/bigfile -v"
  end
end
